<?php

namespace app\admin\controller;

use think\exception\HttpResponseException;

class AdminBase extends \app\BaseController
{
        public  $adminUser=null;
        public function initialize()
        {
            parent::initialize(); // TODO: Change the autogenerated stub

//            if (empty($this->isLogIn())){
//                 return $this->redirect(url('login/index'));
//            }
        }

        public  function isLogIn()
        {

            $this->adminUser=session(config('admin.session_admin'));
            if (empty($this->adminUser)){
                return false;
            }
            return  true;
        }

        public  function  redirect(...$args)
        {
            throw new  HttpResponseException(redirect(...$args));
        }

}