<?php

/**
 *  api模块下的公共控制器，不需要登录继承这个
 *  需要登录 继承AuthBase
 */
namespace app\api\controller;
use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase extends  BaseController
{
    public  function  initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public  function  show(...$args)
    {
            throw  new HttpResponseException(show(...$args));
    }
}