<?php

namespace app\api\controller;

use http\Header;

class AuthBase extends ApiBase
{
    public $userId = 0;
    public $username = "";
    public $accessToken = "";
    public $isLogin = 1;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->accessToken = $this->request->header('access-token');
        if ($this->isLogin==1){
            $this->userId='20';//测试场景
            return true;
        }
        if (!$this->accessToken || !$this->isLogin()) {
            return $this->show(config('status.error'), '没有登录');
        }

    }

    /** 判断用户是否登录
     * @return bool
     */
    public function isLogin()
    {
        $userInfo = cache(config('redis.token_pre') . $this->accessToken);
        if (!$userInfo) {
            return false;
        }
        if (!empty($userInfo['id']) && !empty($userInfo['username'])) {
            $this->username = $userInfo['username'];
            $this->userId = $userInfo['id'];
            return true;
        }
        return false;
    }
}